config/routes.rb
Money::Application.routes.draw do
  devise_for :users

  resources :home
  resources :expense
  resources :account

  match ':controller(/:action(/:id))(.:format)'
  root :to => 'home#welcome'
end

app/models/account.rb
class Account < ActiveRecord::Base
	attr_accessible :description, :name, :not_count, :account_type, :user_id, :balance
	validates_presence_of :account_type, :message => "必須選擇帳戶種類"
	validates_presence_of :name, :message => "帳戶名稱不能為空白"
	validates_presence_of :balance, :message => "必須輸入餘額，至少為 0"
	scope :cash, where( :account_type => "cash" )
	scope :credit_card, where( :account_type => "credit_card" )
	scope :bank, where( :account_type => "bank" )
	scope :emoney, where( :account_type => "emoney" )
	scope :sum_balance, sum( :balance )
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
	before_filter :authenticate_user!
	def index
		@all_user_accounts = Account.where(:user_id => current_user.id)

		@uid = current_user.id
	end
	def new
		@account = Account.new
	end
	def edit
		@account = Account.find(params[:id])
	end
	def create
		@account = Account.new(params[:account])
		@account.user_id = current_user.id
		if @account.save
			redirect_to :action => :index
		else
			render :action => :new
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expense_controller.rb
class ExpenseController < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	def home
	end
	def show
	end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def javascript(*files)
    	content_for(:head) { javascript_include_tag(*files) }
  	end
end

app/helpers/expense_helper.rb
module ExpenseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
:erb
	<% provide(:bodyclass, "home") %>

.container-fluid.animated.fadeInDown
	#header-home 
		Balance $12,345
		- if user_signed_in?
			.pull-right
				= link_to raw("<i class='icon-signout'></i>"), destroy_user_session_path, :method => :delete, :class => "btn btn-mini btn-info" 

	%ul#tool
		%li#expense
			= link_to "新增支出", expense_index_path
		%li#account
			= link_to "帳戶總覽", account_index_path
		%li#income
			= link_to "帳戶總覽", "account_index_path"

app/views/home/welcome.html.haml
:erb
	<% provide(:bodyclass, "index") %>

#welcome
	%h1#icon Flat Money

:javascript
	 $("#title").fitText();
	 setTimeout('window.location.href="home/"', 1000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Money</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="user-scalable=0, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes" />
</head>
<body class="<%= yield(:bodyclass) %>">

<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

<%= yield %>

</body>
</html>